Revert "B #-: Fixes onegate requests adding content-type header (#233)"
This reverts commit fabec869d49a0c0fc5e712f354eccf219d414439.

diff --git a/context-linux/src/etc/one-context.d/net-99-report-ready b/context-linux/src/etc/one-context.d/net-99-report-ready
--- a/context-linux/src/etc/one-context.d/net-99-report-ready
+++ b/context-linux/src/etc/one-context.d/net-99-report-ready
@@ -32,13 +32,43 @@ fi
 
 ###
 
-if ! command -v onegate ; then
-    echo "ERROR: No way to signal READY=YES (onegate binary not found)" >&2
+if command -v curl ; then
+    _command=curl
+elif command -v wget && ! wget --help 2>&1 | grep -q BusyBox; then
+    _command=wget
+elif command -v onegate ; then
+    _command=onegate
+else
+    echo "ERROR: No way to signal READY=YES (no usable binary)" >&2
     exit 1
 fi > /dev/null # this will not drop the error message which goes to stderr
 
 report_ready() {
-    onegate vm update --data "READY=YES"
+    case "$_command" in
+        curl)
+            curl -X "PUT" "${ONEGATE_ENDPOINT}/vm" \
+                --header "X-ONEGATE-TOKEN: $TOKENTXT" \
+                --header "X-ONEGATE-VMID: $VMID" \
+                --max-time 10 \
+                --insecure \
+                -d "READY=YES"
+            ;;
+        wget)
+            wget --method=PUT "${ONEGATE_ENDPOINT}/vm" \
+                --body-data="READY=YES" \
+                --header "X-ONEGATE-TOKEN: $TOKENTXT" \
+                --header "X-ONEGATE-VMID: $VMID" \
+                --timeout=10 \
+                --no-check-certificate
+            ;;
+        onegate)
+            if command -v timeout >/dev/null; then
+                timeout 10 onegate vm update --data "READY=YES"
+            else
+                onegate vm update --data "READY=YES"
+            fi
+            ;;
+    esac
 }
 
 is_base64() {
