Improve READY_SCRIPT handling and add READY_SCRIPT_PATH

diff --git a/context-linux/src/etc/one-context.d/net-99-report-ready b/context-linux/src/etc/one-context.d/net-99-report-ready
--- a/context-linux/src/etc/one-context.d/net-99-report-ready
+++ b/context-linux/src/etc/one-context.d/net-99-report-ready
@@ -71,17 +71,47 @@ report_ready() {
     esac
 }
 
-while [ "$RETRY_COUNT" -gt 0 ] ; do
-    if [[ -n "$READY_SCRIPT" ]];then
-        if eval "$READY_SCRIPT";then
+is_base64() {
+    [[ $1 =~ ^([A-Za-z0-9+/]{4})*([A-Za-z0-9+/]{3}=|[A-Za-z0-9+/]{2}==)?$ ]]
+}
+
+log_ready_error() {
+    echo "$1" failed to execute. Not reporting READY on attempt "$RETRY_COUNT" >&2
+    false # force fail for retry
+}
+
+if [ -n "$READY_SCRIPT_PATH" ]; then
+    if [ -e "$READY_SCRIPT_PATH" ]; then
+        ready_method() {
+            if "$READY_SCRIPT_PATH"; then
+                report_ready
+            else
+                log_ready_error "$READY_SCRIPT_PATH"
+            fi
+        }
+    else
+        echo "$READY_SCRIPT_PATH" does not exist >&2
+        exit 1
+    fi
+elif [ -n "$READY_SCRIPT" ]; then
+    # Can lead to butchering of simple non encoded commands, Ex. echo
+    is_base64 "$READY_SCRIPT" && READY_SCRIPT=$(echo "$READY_SCRIPT" | base64 -d)
+
+    ready_method() {
+        if (eval "$READY_SCRIPT"); then
             report_ready
         else
-            echo READY_SCRIPT "$READY_SCRIPT" failed to execute. Not reporting READY on attempt "$RETRY_COUNT" >&2
-            asdf &>/dev/null # force fail for retry
+            log_ready_error "READY_SCRIPT"
         fi
-    else
+    }
+else
+    ready_method() {
         report_ready
-    fi
+    }
+fi
+
+while [ "$RETRY_COUNT" -gt 0 ] ; do
+    ready_method
 
     # shellcheck disable=SC2181
     if [ "$?" = "0" ]; then
